### PR TITLE
Refactor to use JavaScript classes

### PR DESCRIPTION
**Pull request by jodavid444**
# Amend index.html file

- [x] Add a div to wrap up the form section 
- [x]  Add an h2 element above the form section

# Amend style.css  file

- [x] update styling for the home page
- [x] Implemented required instruction, add li tag

# Amend app.js file

- [x] Update app.js file, use javascript classes to refractor javascript file
- [x]  Implemented required changes

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Joe, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not contributed by all 2 assigned pair group members. Kindly ensure that **all** assigned pair members contribute evenly to this project, and then kindly request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jodavid444** [comment]
@rloterh 
Hello Mr rloterh my coding partner wasn't present this week I reached out to him countless times but I only got a reply from him saying that they had a protest going on in his country, and he wasn't feeling fine that was why he wasn't present and he schedules a day for us to meet but he wasn't present.

**Comment by jodavid444** [comment]
Hello I understand what you're saying  but I reached out to my coding
partner this week but he wasn't present, I sent him a message on slack and
I got a reply from him saying that he was not feeling fine and his country
had a protest which is affecting his absent, we schedule to meet again but
he wasn't present

**Comment by rloterh** [comment]
@jodavid444 
I think you should have first reported this issue to the student success team via the Zendesk earlier on. However, I'll escalate this issue to my leaders, and hope this can probably be resolved soon.

**Comment by rloterh** [comment]
@jodavid444 
Apparently, before you can proceed to work/ submit this project alone, it's very important that you first get the approval of the Student Success team. I suggest you raise a ticket for the same regarding this issue via the Zendesk.

**Pull request merged**
